
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDEumYMo2VjDlVGKyQuiw58Tjd_-0Bt3E',
    appId: '1:275196114055:android:76491125be2cdccfc4b422',
    messagingSenderId: '275196114055',
    projectId: 'isetn-93886',
    storageBucket: 'isetn-93886.firebasestorage.app'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdq-Jiottrd_64ZhHlcO5Daq6ytOm6THg',
    authDomain: 'isetn-93886.firebaseapp.com',
    projectId: 'isetn-93886',
    storageBucket: 'isetn-93886.firebasestorage.app',
    messagingSenderId: '275196114055',
    appId: '1:275196114055:web:918e024a6d994474c4b422'
  );
}
