plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services' // Ajout du plugin Firebase
}

android {
    namespace "com.example.GeoISETN" // Assure-toi que c'est bien le même nom que ton package
    compileSdk 34

    defaultConfig {
        applicationId "com.example.GeoISETN"
        minSdk 21
        targetSdk 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.9.0') // BoM Firebase pour gérer les versions automatiquement
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-database'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
